import { Product } from '@/types/product';

export const mockProducts: Product[] = [
  // Apple iPhones
  {
    id: '1',
    name: 'iPhone 15 Pro Max',
    slug: 'iphone-15-pro-max',
    brand: 'Apple',
    category: 'Phone',
    images: [
  '/products/iphone-15-pro-max.jpg',
  '/products/iphone-15-pro-max.jpg',
  '/products/iphone-15-pro-max.jpg',
  '/products/iphone-15-pro-max.jpg'
],
    price: 145000,
    offerPrice: 139000,
    condition: 'Brand New',
    tags: ['Hot', 'Best Deal'],
    productCode: 'IP15PM-001',
    stock: 5,
    warranty: '1 Year Official Warranty',
    description: 'iPhone 15 Pro Max features a titanium design, A17 Pro chip, and advanced camera system.',
    rating: 4.8,
    reviewCount: 12,
    reviews: [
      {
        id: 'r1',
        userId: 'u1',
        userName: 'Karim Ahmed',
        rating: 5,
        comment: 'Excellent phone! Camera quality is amazing and battery life is great. Highly recommended!',
        date: '2024-01-15',
        verified: true,
      },
      {
        id: 'r2',
        userId: 'u2',
        userName: 'Fatima Rahman',
        rating: 5,
        comment: 'Best iPhone yet! The titanium design feels premium and the performance is incredible.',
        date: '2024-01-10',
        verified: true,
      },
      {
        id: 'r3',
        userId: 'u3',
        userName: 'Rahim Khan',
        rating: 4,
        comment: 'Great phone but a bit expensive. Overall satisfied with the purchase.',
        date: '2024-01-05',
        verified: true,
      },
    ],
    variants: [
      { storage: '256GB', color: 'Natural Titanium', region: 'USA', price: 139000, stock: 3 },
      { storage: '512GB', color: 'Blue Titanium', region: 'USA', price: 159000, stock: 2 },
      { storage: '1TB', color: 'Black Titanium', region: 'USA', price: 179000, stock: 1 },
    ],
  },
  {
    id: '2',
    name: 'iPhone 15 Pro',
    slug: 'iphone-15-pro',
    brand: 'Apple',
    category: 'Phone',
    images: ['/products/iphone-15-pro.jpg'],
    price: 125000,
    offerPrice: 119000,
    condition: 'Brand New',
    tags: ['Hot'],
    productCode: 'IP15P-001',
    stock: 8,
    warranty: '1 Year Official Warranty',
    variants: [
      { storage: '128GB', color: 'Natural Titanium', region: 'USA', price: 119000, stock: 4 },
      { storage: '256GB', color: 'Blue Titanium', region: 'USA', price: 129000, stock: 4 },
    ],
  },
  {
    id: '3',
    name: 'iPhone 15',
    slug: 'iphone-15',
    brand: 'Apple',
    category: 'Phone',
    images: ['/products/iphone-15.jpg'],
    price: 95000,
    offerPrice: 89000,
    condition: 'Brand New',
    tags: ['Best Deal'],
    productCode: 'IP15-001',
    stock: 12,
    warranty: '1 Year Official Warranty',
    variants: [
      { storage: '128GB', color: 'Black', region: 'USA', price: 89000, stock: 6 },
      { storage: '256GB', color: 'Blue', region: 'USA', price: 99000, stock: 6 },
    ],
  },
  {
    id: '4',
    name: 'iPhone 14 Pro Max',
    slug: 'iphone-14-pro-max',
    brand: 'Apple',
    category: 'Phone',
    images: ['/products/iphone-14-pro-max.jpg'],
    price: 115000,
    offerPrice: 109000,
    condition: 'Brand New',
    tags: ['Trending'],
    productCode: 'IP14PM-001',
    stock: 6,
    warranty: '1 Year Official Warranty',
  },
  {
    id: '5',
    name: 'iPhone 16 Pro',
    slug: 'iphone-16-pro',
    brand: 'Apple',
    category: 'Phone',
    images: ['/products/iphone-16-pro.jpg'],
    price: 165000,
    condition: 'Brand New',
    tags: ['New Arrival'],
    productCode: 'IP16P-PRE',
    stock: 0,
    isPreOrder: true,
    deliveryDays: 7,
    warranty: '1 Year Official Warranty',
  },
  
  // Samsung Phones
  {
    id: '6',
    name: 'Samsung Galaxy S24 Ultra',
    slug: 'samsung-galaxy-s24-ultra',
    brand: 'Samsung',
    category: 'Phone',
    images: ['/products/samsung-s24-ultra.jpg'],
    price: 135000,
    offerPrice: 129000,
    condition: 'Brand New',
    tags: ['New Arrival', 'Hot'],
    productCode: 'SGS24U-001',
    stock: 8,
    warranty: '1 Year Official Warranty',
    variants: [
      { storage: '256GB', color: 'Titanium Gray', region: 'UK', price: 129000, stock: 5 },
      { storage: '512GB', color: 'Titanium Black', region: 'UK', price: 149000, stock: 3 },
    ],
  },
  {
    id: '7',
    name: 'Samsung Galaxy S24+',
    slug: 'samsung-galaxy-s24-plus',
    brand: 'Samsung',
    category: 'Phone',
    images: ['/products/samsung-s24-plus.jpg'],
    price: 105000,
    condition: 'Brand New',
    tags: ['New Arrival'],
    productCode: 'SGS24P-001',
    stock: 10,
    warranty: '1 Year Official Warranty',
  },
  {
    id: '8',
    name: 'Samsung Galaxy S23 Ultra',
    slug: 'samsung-galaxy-s23-ultra',
    brand: 'Samsung',
    category: 'Phone',
    images: ['/products/samsung-s23-ultra.jpg'],
    price: 115000,
    offerPrice: 105000,
    condition: 'Brand New',
    tags: ['Best Deal'],
    productCode: 'SGS23U-001',
    stock: 5,
    warranty: '1 Year Official Warranty',
  },
  {
    id: '9',
    name: 'Samsung Galaxy Z Fold 5',
    slug: 'samsung-galaxy-z-fold-5',
    brand: 'Samsung',
    category: 'Phone',
    images: ['/products/samsung-z-fold-5.jpg'],
    price: 185000,
    offerPrice: 175000,
    condition: 'Brand New',
    tags: ['Hot', 'Trending'],
    productCode: 'SGZF5-001',
    stock: 3,
    warranty: '1 Year Official Warranty',
  },
  {
    id: '10',
    name: 'Samsung Galaxy Z Flip 5',
    slug: 'samsung-galaxy-z-flip-5',
    brand: 'Samsung',
    category: 'Phone',
    images: ['/products/samsung-z-flip-5.jpg'],
    price: 125000,
    condition: 'Brand New',
    tags: ['Trending'],
    productCode: 'SGZFL5-001',
    stock: 4,
    warranty: '1 Year Official Warranty',
  },

  // Google Pixels
  {
    id: '11',
    name: 'Google Pixel 8 Pro',
    slug: 'google-pixel-8-pro',
    brand: 'Google',
    category: 'Phone',
    images: ['/products/google-pixel-8-pro.jpg'],
    price: 95000,
    offerPrice: 89000,
    condition: 'Brand New',
    tags: ['Trending', 'Best Deal'],
    productCode: 'GP8P-001',
    stock: 7,
    warranty: '1 Year Official Warranty',
  },
  {
    id: '12',
    name: 'Google Pixel 8',
    slug: 'google-pixel-8',
    brand: 'Google',
    category: 'Phone',
    images: ['/products/google-pixel-8.jpg'],
    price: 75000,
    offerPrice: 69000,
    condition: 'Brand New',
    tags: ['Best Deal'],
    productCode: 'GP8-001',
    stock: 10,
    warranty: '1 Year Official Warranty',
  },
  {
    id: '13',
    name: 'Google Pixel 7 Pro',
    slug: 'google-pixel-7-pro',
    brand: 'Google',
    category: 'Phone',
    images: ['/products/google-pixel-7-pro.jpg'],
    price: 79000,
    offerPrice: 72000,
    condition: 'Brand New',
    tags: ['Best Deal'],
    productCode: 'GP7P-001',
    stock: 6,
    warranty: '1 Year Official Warranty',
  },

  // Other Brands
  {
    id: '14',
    name: 'OnePlus 12',
    slug: 'oneplus-12',
    brand: 'Others',
    category: 'Phone',
    images: ['/products/oneplus-12.jpg'],
    price: 65000,
    offerPrice: 59000,
    condition: 'Brand New',
    tags: ['New Arrival'],
    productCode: 'OP12-001',
    stock: 8,
    warranty: '1 Year Official Warranty',
  },
  {
    id: '15',
    name: 'Xiaomi 14 Pro',
    slug: 'xiaomi-14-pro',
    brand: 'Others',
    category: 'Phone',
    images: ['/products/xiaomi-14-pro.jpg'],
    price: 55000,
    offerPrice: 49000,
    condition: 'Brand New',
    tags: ['Best Deal'],
    productCode: 'XM14P-001',
    stock: 12,
    warranty: '1 Year Official Warranty',
  },

  // Apple Accessories
  {
    id: '16',
    name: 'Apple AirPods Pro 2',
    slug: 'airpods-pro-2',
    brand: 'Apple',
    category: 'Earphone',
    images: ['/products/airpods-pro-2.jpg'],
    price: 28000,
    offerPrice: 25500,
    condition: 'Brand New',
    tags: ['Best Deal', 'Hot'],
    productCode: 'APP2-001',
    stock: 15,
    warranty: '1 Year Official Warranty',
  },
  {
    id: '17',
    name: 'Apple AirPods 3',
    slug: 'airpods-3',
    brand: 'Apple',
    category: 'Earphone',
    images: ['/products/airpods-3.jpg'],
    price: 18000,
    offerPrice: 16500,
    condition: 'Brand New',
    tags: ['Best Deal'],
    productCode: 'AP3-001',
    stock: 20,
    warranty: '1 Year Official Warranty',
  },
  {
    id: '18',
    name: 'Apple AirPods Max',
    slug: 'airpods-max',
    brand: 'Apple',
    category: 'Earphone',
    images: ['/products/airpods-max.jpg'],
    price: 58000,
    condition: 'Brand New',
    tags: ['Hot'],
    productCode: 'APM-001',
    stock: 5,
    warranty: '1 Year Official Warranty',
  },
  {
    id: '19',
    name: 'Apple Watch Series 9',
    slug: 'apple-watch-series-9',
    brand: 'Apple',
    category: 'Accessories',
    images: ['/products/apple-watch-9.jpg'],
    price: 45000,
    offerPrice: 42000,
    condition: 'Brand New',
    tags: ['New Arrival'],
    productCode: 'AW9-001',
    stock: 8,
    warranty: '1 Year Official Warranty',
  },
  {
    id: '20',
    name: 'Apple Watch Ultra 2',
    slug: 'apple-watch-ultra-2',
    brand: 'Apple',
    category: 'Accessories',
    images: ['/products/apple-watch-ultra-2.jpg'],
    price: 85000,
    condition: 'Brand New',
    tags: ['Hot'],
    productCode: 'AWU2-001',
    stock: 4,
    warranty: '1 Year Official Warranty',
  },

  // Chargers
  {
    id: '21',
    name: '20W USB-C Power Adapter',
    slug: '20w-usb-c-adapter',
    brand: 'Apple',
    category: 'Charger',
    images: ['/products/20w-adapter.jpg'],
    price: 2500,
    condition: 'Brand New',
    productCode: 'AC20W-001',
    stock: 50,
    warranty: '6 Months Warranty',
  },
  {
    id: '22',
    name: '35W Dual USB-C Adapter',
    slug: '35w-dual-usb-c-adapter',
    brand: 'Apple',
    category: 'Charger',
    images: ['/products/35w-adapter.jpg'],
    price: 4500,
    condition: 'Brand New',
    productCode: 'AC35W-001',
    stock: 30,
    warranty: '6 Months Warranty',
  },
  {
    id: '23',
    name: '45W Fast Charger',
    slug: '45w-fast-charger',
    brand: 'Samsung',
    category: 'Charger',
    images: ['/products/45w-charger.jpg'],
    price: 3500,
    offerPrice: 2999,
    condition: 'Brand New',
    tags: ['Best Deal'],
    productCode: 'SC45W-001',
    stock: 40,
    warranty: '6 Months Warranty',
  },

  // Power Banks
  {
    id: '24',
    name: '20000mAh Power Bank',
    slug: '20000mah-power-bank',
    brand: 'Others',
    category: 'Power Bank',
    images: ['/products/power-bank-20000.jpg'],
    price: 3500,
    offerPrice: 2999,
    condition: 'Brand New',
    tags: ['Best Deal'],
    productCode: 'PB20K-001',
    stock: 25,
    warranty: '1 Year Warranty',
  },
  {
    id: '25',
    name: '10000mAh Wireless Power Bank',
    slug: '10000mah-wireless-power-bank',
    brand: 'Others',
    category: 'Power Bank',
    images: ['/products/power-bank-10000.jpg'],
    price: 2500,
    offerPrice: 1999,
    condition: 'Brand New',
    tags: ['Best Deal'],
    productCode: 'PB10K-001',
    stock: 35,
    warranty: '1 Year Warranty',
  },

  // Phone Cases
  {
    id: '26',
    name: 'iPhone 15 Pro Max Silicone Case',
    slug: 'iphone-15-pro-max-case',
    brand: 'Apple',
    category: 'Cover',
    images: ['/products/iphone-15-case.jpg'],
    price: 4500,
    condition: 'Brand New',
    productCode: 'IPC15PM-001',
    stock: 30,
  },
  {
    id: '27',
    name: 'Samsung S24 Ultra Clear Case',
    slug: 'samsung-s24-ultra-case',
    brand: 'Samsung',
    category: 'Cover',
    images: ['/products/samsung-s24-case.jpg'],
    price: 2500,
    offerPrice: 1999,
    condition: 'Brand New',
    tags: ['Best Deal'],
    productCode: 'SCC24U-001',
    stock: 40,
  },

  // Screen Protectors
  {
    id: '28',
    name: 'Tempered Glass Screen Protector',
    slug: 'tempered-glass-protector',
    brand: 'Others',
    category: 'Glass',
    images: ['/products/screen-protector.jpg'],
    price: 800,
    offerPrice: 599,
    condition: 'Brand New',
    tags: ['Best Deal'],
    productCode: 'TG-001',
    stock: 100,
  },
  {
    id: '29',
    name: 'Privacy Glass Screen Protector',
    slug: 'privacy-glass-protector',
    brand: 'Others',
    category: 'Glass',
    images: ['/products/privacy-glass.jpg'],
    price: 1200,
    offerPrice: 999,
    condition: 'Brand New',
    tags: ['Best Deal'],
    productCode: 'PG-001',
    stock: 50,
  },

  // More Earphones
  {
    id: '30',
    name: 'Samsung Galaxy Buds 2 Pro',
    slug: 'samsung-galaxy-buds-2-pro',
    brand: 'Samsung',
    category: 'Earphone',
    images: ['/products/galaxy-buds-2-pro.jpg'],
    price: 18000,
    offerPrice: 15999,
    condition: 'Brand New',
    tags: ['Best Deal'],
    productCode: 'SGB2P-001',
    stock: 12,
    warranty: '1 Year Official Warranty',
  },
];

export const categories = [
  { name: 'Phone', icon: '📱', count: 15 },
  { name: 'Accessories', icon: '🎧', count: 2 },
  { name: 'Charger', icon: '🔌', count: 3 },
  { name: 'Earphone', icon: '🎧', count: 5 },
  { name: 'Power Bank', icon: '🔋', count: 2 },
  { name: 'Cover', icon: '📦', count: 2 },
  { name: 'Glass', icon: '🛡️', count: 2 },
];

export const brands = ['Apple', 'Samsung', 'Google', 'Others'];
