import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { SeedService } from './seed.service';
import {
  User,
  Branch,
  Brand,
  Supplier,
  LocalSeller,
  Customer,
  ExpenseCategory,
  Carrier,
  Investor,
  Product,
  ProductVariant,
  ProductDamage,
  Sale,
  SaleItem,
  Payment,
  Expense,
  ServiceJob,
  ServicePart,
  ServiceDueCollection,
  OverseasPhoneTracking,
  OverseasPhoneStatusHistory,
  PreOrder,
  InvestmentPayout,
  SupplierPayment,
  DueCollection,
} from '../entities';

@Module({
  imports: [
    TypeOrmModule.forFeature([
      User,
      Branch,
      Brand,
      Supplier,
      LocalSeller,
      Customer,
      ExpenseCategory,
      Carrier,
      Investor,
      Product,
      ProductVariant,
      ProductDamage,
      Sale,
      SaleItem,
      Payment,
      Expense,
      ServiceJob,
      ServicePart,
      ServiceDueCollection,
      OverseasPhoneTracking,
      OverseasPhoneStatusHistory,
      PreOrder,
      InvestmentPayout,
      SupplierPayment,
      DueCollection,
    ]),
  ],
  providers: [SeedService],
  exports: [SeedService],
})
export class SeedModule {}
