import {
  UserRole,
  ProductCategory,
  PhoneType,
  AccessoryType,
  ProductStatus,
  PaymentMethod,
  PaymentStatus,
  ServiceStatus,
  ServiceType,
  PartsUsageType,
  InvestmentType,
  PayoutMethod,
  InvestorStatus,
  OverseasPhoneStatus,
  SourceType,
  ContractType,
  ExpenseType,
  ProductCondition,
  PhoneRegion,
  OrderStatus,
  EmiDuration,
} from '../../common/constants';

// Helper to generate dates
const daysAgo = (days: number) => {
  const date = new Date();
  date.setDate(date.getDate() - days);
  return date;
};

const daysFromNow = (days: number) => {
  const date = new Date();
  date.setDate(date.getDate() + days);
  return date;
};

// Branch Data
export const branchesData = [
  {
    name: 'Main Branch - Dhaka',
    address: '123 Motijheel, Dhaka-1000',
    phone: '01711111111',
    isActive: true,
  },
  {
    name: 'Chittagong Branch',
    address: '45 GEC Circle, Chittagong',
    phone: '01722222222',
    isActive: true,
  },
  {
    name: 'Sylhet Branch',
    address: '78 Zindabazar, Sylhet',
    phone: '01733333333',
    isActive: false,
  },
];

// Users Data (passwords will be hashed: "password123")
export const usersData = [
  {
    name: 'Admin User',
    email: 'admin@mobileganj.com',
    phone: '01811111111',
    password: 'password123',
    role: UserRole.ADMIN,
    isActive: true,
    branchIndex: 0,
  },
  {
    name: 'Staff Member 1',
    email: 'staff1@mobileganj.com',
    phone: '01822222222',
    password: 'password123',
    role: UserRole.STAFF,
    isActive: true,
    branchIndex: 0,
  },
  {
    name: 'Staff Member 2',
    email: 'staff2@mobileganj.com',
    phone: '01833333333',
    password: 'password123',
    role: UserRole.STAFF,
    isActive: true,
    branchIndex: 1,
  },
];

// Brands Data
export const brandsData = [
  { name: 'Apple', logo: undefined, isActive: true },
  { name: 'Samsung', logo: undefined, isActive: true },
  { name: 'Xiaomi', logo: undefined, isActive: true },
  { name: 'OnePlus', logo: undefined, isActive: true },
  { name: 'Google', logo: undefined, isActive: true },
  { name: 'Oppo', logo: undefined, isActive: true },
  { name: 'Vivo', logo: undefined, isActive: true },
  { name: 'Realme', logo: undefined, isActive: true },
];

// Suppliers Data
export const suppliersData = [
  {
    name: 'Dubai Mobile Imports',
    phone: '01911111111',
    address: 'Dubai, UAE',
    shopName: 'Global Mobile Hub',
    note: 'Main overseas supplier',
  },
  {
    name: 'Local Tech Supplier',
    phone: '01922222222',
    address: 'Dhaka, Bangladesh',
    shopName: 'Tech Mart BD',
    note: 'Local distributor',
  },
  {
    name: 'Japan Direct',
    phone: '01933333333',
    address: 'Tokyo, Japan',
    shopName: 'Tokyo Mobile',
    note: 'Japanese imports',
  },
];

// Local Sellers Data
export const localSellersData = [
  {
    fullName: 'Mohammad Rahman',
    fatherName: 'Abdul Rahman',
    motherName: 'Fatima Begum',
    phone: '01611111111',
    address: 'Mirpur, Dhaka',
    nidNumber: '1234567890123',
  },
  {
    fullName: 'Karim Sheikh',
    fatherName: 'Sheikh Ahmed',
    motherName: 'Ayesha Khatun',
    phone: '01622222222',
    address: 'Uttara, Dhaka',
    nidNumber: '9876543210987',
  },
];

// Customers Data
export const customersData = [
  { name: 'Rahim Ahmed', phone: '01511111111', address: 'Dhanmondi, Dhaka' },
  { name: 'Karim Hossain', phone: '01522222222', address: 'Gulshan, Dhaka' },
  { name: 'Fatima Begum', phone: '01533333333', address: 'Mohammadpur, Dhaka' },
  { name: 'Abdul Kader', phone: '01544444444', address: 'Mirpur, Dhaka' },
  { name: 'Nasreen Akter', phone: '01555555555', address: 'Banani, Dhaka' },
  { name: 'Jahid Islam', phone: '01566666666', address: 'Uttara, Dhaka' },
  { name: 'Salma Khatun', phone: '01577777777', address: 'Badda, Dhaka' },
  { name: 'Rafiq Mia', phone: '01588888888', address: 'Tejgaon, Dhaka' },
];

// Expense Categories Data
export const expenseCategoriesData = [
  {
    name: 'Shop Rent',
    type: ExpenseType.FIXED,
    isSystem: true,
    isActive: true,
  },
  {
    name: 'Electricity Bill',
    type: ExpenseType.FIXED,
    isSystem: true,
    isActive: true,
  },
  {
    name: 'Internet Bill',
    type: ExpenseType.FIXED,
    isSystem: true,
    isActive: true,
  },
  {
    name: 'Staff Salary',
    type: ExpenseType.FIXED,
    isSystem: true,
    isActive: true,
  },
  {
    name: 'Office Supplies',
    type: ExpenseType.UNFIXED,
    isSystem: false,
    isActive: true,
  },
  {
    name: 'Transport',
    type: ExpenseType.UNFIXED,
    isSystem: false,
    isActive: true,
  },
  {
    name: 'Marketing',
    type: ExpenseType.UNFIXED,
    isSystem: false,
    isActive: true,
  },
  {
    name: 'Miscellaneous',
    type: ExpenseType.UNFIXED,
    isSystem: false,
    isActive: true,
  },
];

// Carriers Data
export const carriersData = [
  {
    name: 'Sky Express Cargo',
    phone: '01411111111',
    location: 'Dubai',
    note: 'Main cargo partner',
    isActive: true,
  },
  {
    name: 'Fast Air Shipping',
    phone: '01422222222',
    location: 'Dubai',
    note: 'Budget shipping',
    isActive: true,
  },
  {
    name: 'Japan Post Direct',
    phone: '01433333333',
    location: 'Japan',
    note: 'Japan imports',
    isActive: true,
  },
];

// Investors Data
export const investorsData = [
  {
    name: 'Mr. Investor One',
    phone: '01311111111',
    address: 'Banani, Dhaka',
    investmentAmount: 500000,
    investmentDate: daysAgo(180),
    investmentType: InvestmentType.FIXED_PROFIT,
    monthlyProfitAmount: 10000,
    profitPercentage: undefined,
    payoutDurationMonths: 12,
    payoutMethod: PayoutMethod.MONTHLY,
    totalInstallmentCount: 12,
    note: 'First major investor',
    status: InvestorStatus.ACTIVE,
  },
  {
    name: 'Mrs. Investor Two',
    phone: '01322222222',
    address: 'Gulshan, Dhaka',
    investmentAmount: 300000,
    investmentDate: daysAgo(90),
    investmentType: InvestmentType.PROFIT_SHARE,
    monthlyProfitAmount: undefined,
    profitPercentage: 5,
    payoutDurationMonths: 6,
    payoutMethod: PayoutMethod.MONTHLY,
    totalInstallmentCount: 6,
    note: 'Profit sharing investor',
    status: InvestorStatus.ACTIVE,
  },
];

// Products Data
export const productsData = [
  // Phones
  {
    title: 'iPhone 15 Pro Max 256GB',
    category: ProductCategory.PHONE,
    phoneType: PhoneType.OVERSEAS,
    accessoryType: undefined,
    brandIndex: 0, // Apple
    imei1: '123456789012345',
    imei2: '123456789012346',
    barcode: 'IP15PM256-001',
    purchasePrice: 145000,
    sellingPrice: 165000,
    offerPrice: 160000,
    stockQty: 3,
    status: ProductStatus.IN_STOCK,
    condition: ProductCondition.BRAND_NEW,
    region: PhoneRegion.USA,
    storage: '256GB',
    ram: '8GB',
    color: 'Natural Titanium',
    warrantyMonths: 12,
    isFeatured: true,
    isNewArrival: true,
    supplierIndex: 0,
    branchIndex: 0,
  },
  {
    title: 'iPhone 14 Pro 128GB',
    category: ProductCategory.PHONE,
    phoneType: PhoneType.OVERSEAS,
    accessoryType: undefined,
    brandIndex: 0, // Apple
    imei1: '223456789012345',
    imei2: '223456789012346',
    barcode: 'IP14P128-001',
    purchasePrice: 115000,
    sellingPrice: 130000,
    offerPrice: undefined,
    stockQty: 2,
    status: ProductStatus.IN_STOCK,
    condition: ProductCondition.BRAND_NEW,
    region: PhoneRegion.JAPAN,
    storage: '128GB',
    ram: '6GB',
    color: 'Deep Purple',
    warrantyMonths: 12,
    isFeatured: true,
    supplierIndex: 2,
    branchIndex: 0,
  },
  {
    title: 'Samsung Galaxy S24 Ultra 512GB',
    category: ProductCategory.PHONE,
    phoneType: PhoneType.OVERSEAS,
    accessoryType: undefined,
    brandIndex: 1, // Samsung
    imei1: '323456789012345',
    imei2: '323456789012346',
    barcode: 'SGS24U512-001',
    purchasePrice: 135000,
    sellingPrice: 155000,
    offerPrice: 150000,
    stockQty: 4,
    status: ProductStatus.IN_STOCK,
    condition: ProductCondition.BRAND_NEW,
    region: PhoneRegion.USA,
    storage: '512GB',
    ram: '12GB',
    color: 'Titanium Black',
    warrantyMonths: 12,
    isFeatured: true,
    isNewArrival: true,
    supplierIndex: 0,
    branchIndex: 0,
  },
  {
    title: 'Xiaomi 14 Pro 256GB',
    category: ProductCategory.PHONE,
    phoneType: PhoneType.OVERSEAS,
    accessoryType: undefined,
    brandIndex: 2, // Xiaomi
    imei1: '423456789012345',
    imei2: '423456789012346',
    barcode: 'XI14P256-001',
    purchasePrice: 75000,
    sellingPrice: 90000,
    offerPrice: 85000,
    stockQty: 5,
    status: ProductStatus.IN_STOCK,
    condition: ProductCondition.BRAND_NEW,
    region: PhoneRegion.OTHER,
    storage: '256GB',
    ram: '12GB',
    color: 'Black',
    warrantyMonths: 6,
    isTrending: true,
    supplierIndex: 1,
    branchIndex: 0,
  },
  {
    title: 'OnePlus 12 256GB',
    category: ProductCategory.PHONE,
    phoneType: PhoneType.OVERSEAS,
    accessoryType: undefined,
    brandIndex: 3, // OnePlus
    imei1: '523456789012345',
    imei2: '523456789012346',
    barcode: 'OP12-256-001',
    purchasePrice: 85000,
    sellingPrice: 100000,
    offerPrice: undefined,
    stockQty: 3,
    status: ProductStatus.IN_STOCK,
    condition: ProductCondition.BRAND_NEW,
    region: PhoneRegion.OTHER,
    storage: '256GB',
    ram: '12GB',
    color: 'Flowy Emerald',
    warrantyMonths: 12,
    supplierIndex: 1,
    branchIndex: 1,
  },
  {
    title: 'Google Pixel 8 Pro 128GB',
    category: ProductCategory.PHONE,
    phoneType: PhoneType.OVERSEAS,
    accessoryType: undefined,
    brandIndex: 4, // Google
    imei1: '623456789012345',
    imei2: '623456789012346',
    barcode: 'GP8P128-001',
    purchasePrice: 95000,
    sellingPrice: 115000,
    offerPrice: 110000,
    stockQty: 2,
    status: ProductStatus.IN_STOCK,
    condition: ProductCondition.BRAND_NEW,
    region: PhoneRegion.USA,
    storage: '128GB',
    ram: '12GB',
    color: 'Bay Blue',
    warrantyMonths: 12,
    isFeatured: true,
    supplierIndex: 0,
    branchIndex: 0,
  },
  {
    title: 'iPhone 13 128GB (Used)',
    category: ProductCategory.PHONE,
    phoneType: PhoneType.LOCAL,
    accessoryType: undefined,
    brandIndex: 0, // Apple
    imei1: '723456789012345',
    imei2: undefined,
    barcode: 'IP13-128-USED-001',
    purchasePrice: 55000,
    sellingPrice: 68000,
    offerPrice: undefined,
    stockQty: 1,
    status: ProductStatus.IN_STOCK,
    condition: ProductCondition.USED,
    region: undefined,
    storage: '128GB',
    ram: '4GB',
    color: 'Blue',
    warrantyMonths: 3,
    localSellerIndex: 0,
    branchIndex: 0,
  },
  // Accessories
  {
    title: 'Apple 20W USB-C Charger',
    category: ProductCategory.ACCESSORIES,
    phoneType: undefined,
    accessoryType: AccessoryType.CHARGER,
    brandIndex: 0, // Apple
    imei1: undefined,
    imei2: undefined,
    barcode: 'ACC-CHRG-001',
    purchasePrice: 1800,
    sellingPrice: 2500,
    offerPrice: undefined,
    stockQty: 20,
    status: ProductStatus.IN_STOCK,
    condition: ProductCondition.BRAND_NEW,
    warrantyMonths: 6,
    supplierIndex: 1,
    branchIndex: 0,
  },
  {
    title: 'Samsung 45W Super Fast Charger',
    category: ProductCategory.ACCESSORIES,
    phoneType: undefined,
    accessoryType: AccessoryType.CHARGER,
    brandIndex: 1, // Samsung
    imei1: undefined,
    imei2: undefined,
    barcode: 'ACC-CHRG-002',
    purchasePrice: 2000,
    sellingPrice: 3000,
    offerPrice: 2800,
    stockQty: 15,
    status: ProductStatus.IN_STOCK,
    condition: ProductCondition.BRAND_NEW,
    warrantyMonths: 6,
    supplierIndex: 1,
    branchIndex: 0,
  },
  {
    title: 'Apple AirPods Pro 2',
    category: ProductCategory.ACCESSORIES,
    phoneType: undefined,
    accessoryType: AccessoryType.EARPHONE,
    brandIndex: 0, // Apple
    imei1: undefined,
    imei2: undefined,
    barcode: 'ACC-EAR-001',
    purchasePrice: 22000,
    sellingPrice: 28000,
    offerPrice: 26000,
    stockQty: 8,
    status: ProductStatus.IN_STOCK,
    condition: ProductCondition.BRAND_NEW,
    warrantyMonths: 12,
    isFeatured: true,
    supplierIndex: 0,
    branchIndex: 0,
  },
  {
    title: 'Xiaomi 20000mAh Power Bank',
    category: ProductCategory.ACCESSORIES,
    phoneType: undefined,
    accessoryType: AccessoryType.POWER_BANK,
    brandIndex: 2, // Xiaomi
    imei1: undefined,
    imei2: undefined,
    barcode: 'ACC-PB-001',
    purchasePrice: 1500,
    sellingPrice: 2200,
    offerPrice: undefined,
    stockQty: 25,
    status: ProductStatus.IN_STOCK,
    condition: ProductCondition.BRAND_NEW,
    warrantyMonths: 6,
    supplierIndex: 1,
    branchIndex: 0,
  },
  {
    title: 'iPhone 15 Pro Max Silicone Case',
    category: ProductCategory.ACCESSORIES,
    phoneType: undefined,
    accessoryType: AccessoryType.COVER,
    brandIndex: 0, // Apple
    imei1: undefined,
    imei2: undefined,
    barcode: 'ACC-CASE-001',
    purchasePrice: 300,
    sellingPrice: 600,
    offerPrice: undefined,
    stockQty: 50,
    status: ProductStatus.IN_STOCK,
    condition: ProductCondition.BRAND_NEW,
    supplierIndex: 1,
    branchIndex: 0,
  },
  {
    title: 'Tempered Glass - Universal',
    category: ProductCategory.ACCESSORIES,
    phoneType: undefined,
    accessoryType: AccessoryType.GLASS,
    brandIndex: undefined,
    imei1: undefined,
    imei2: undefined,
    barcode: 'ACC-GLASS-001',
    purchasePrice: 50,
    sellingPrice: 150,
    offerPrice: undefined,
    stockQty: 100,
    status: ProductStatus.IN_STOCK,
    condition: ProductCondition.BRAND_NEW,
    supplierIndex: 1,
    branchIndex: 0,
  },
];

// Sales Data
export const salesData = [
  {
    invoiceNo: 'INV-2024-0001',
    saleDate: daysAgo(30),
    customerIndex: 0,
    branchIndex: 0,
    userIndex: 1,
    subtotal: 165000,
    discountType: 'fixed' as const,
    discountValue: 5000,
    discountAmount: 5000,
    grandTotal: 160000,
    paidAmount: 160000,
    dueAmount: 0,
    paymentMethod: PaymentMethod.CASH,
    status: PaymentStatus.PAID,
    items: [
      { productIndex: 0, quantity: 1, unitPrice: 165000, totalPrice: 165000 },
    ],
  },
  {
    invoiceNo: 'INV-2024-0002',
    saleDate: daysAgo(25),
    customerIndex: 1,
    branchIndex: 0,
    userIndex: 1,
    subtotal: 155000,
    discountType: 'percentage' as const,
    discountValue: 3,
    discountAmount: 4650,
    grandTotal: 150350,
    paidAmount: 100000,
    dueAmount: 50350,
    dueDate: daysFromNow(30),
    paymentMethod: PaymentMethod.BKASH,
    status: PaymentStatus.PARTIAL_PAID,
    items: [
      { productIndex: 2, quantity: 1, unitPrice: 155000, totalPrice: 155000 },
    ],
  },
  {
    invoiceNo: 'INV-2024-0003',
    saleDate: daysAgo(20),
    customerIndex: 2,
    branchIndex: 0,
    userIndex: 1,
    subtotal: 95500,
    discountType: undefined,
    discountValue: 0,
    discountAmount: 0,
    grandTotal: 95500,
    paidAmount: 95500,
    dueAmount: 0,
    paymentMethod: PaymentMethod.NAGAD,
    status: PaymentStatus.PAID,
    items: [
      { productIndex: 3, quantity: 1, unitPrice: 90000, totalPrice: 90000 },
      { productIndex: 7, quantity: 2, unitPrice: 2500, totalPrice: 5000 },
      { productIndex: 12, quantity: 1, unitPrice: 150, totalPrice: 150 },
    ],
  },
  {
    invoiceNo: 'INV-2024-0004',
    saleDate: daysAgo(15),
    customerIndex: 3,
    branchIndex: 1,
    userIndex: 2,
    subtotal: 100000,
    discountType: 'fixed' as const,
    discountValue: 2000,
    discountAmount: 2000,
    grandTotal: 98000,
    paidAmount: 50000,
    dueAmount: 48000,
    dueDate: daysFromNow(15),
    paymentMethod: PaymentMethod.CASH,
    status: PaymentStatus.PARTIAL_PAID,
    items: [
      { productIndex: 4, quantity: 1, unitPrice: 100000, totalPrice: 100000 },
    ],
  },
  {
    invoiceNo: 'INV-2024-0005',
    saleDate: daysAgo(10),
    customerIndex: 4,
    branchIndex: 0,
    userIndex: 1,
    subtotal: 31200,
    discountType: undefined,
    discountValue: 0,
    discountAmount: 0,
    grandTotal: 31200,
    paidAmount: 31200,
    dueAmount: 0,
    paymentMethod: PaymentMethod.BKASH,
    status: PaymentStatus.PAID,
    items: [
      { productIndex: 9, quantity: 1, unitPrice: 28000, totalPrice: 28000 },
      { productIndex: 10, quantity: 1, unitPrice: 2200, totalPrice: 2200 },
      { productIndex: 11, quantity: 2, unitPrice: 600, totalPrice: 1200 },
    ],
  },
];

// Expenses Data
export const expensesData = [
  {
    categoryIndex: 0,
    amount: 50000,
    paymentMethod: PaymentMethod.BANK,
    expenseDate: daysAgo(30),
    userIndex: 0,
    note: 'Monthly rent',
  },
  {
    categoryIndex: 1,
    amount: 8000,
    paymentMethod: PaymentMethod.BKASH,
    expenseDate: daysAgo(28),
    userIndex: 0,
    note: 'Electricity bill',
  },
  {
    categoryIndex: 2,
    amount: 2500,
    paymentMethod: PaymentMethod.BKASH,
    expenseDate: daysAgo(25),
    userIndex: 0,
    note: 'Internet bill',
  },
  {
    categoryIndex: 3,
    amount: 45000,
    paymentMethod: PaymentMethod.BANK,
    expenseDate: daysAgo(5),
    userIndex: 0,
    note: 'Staff salaries',
  },
  {
    categoryIndex: 4,
    amount: 3000,
    paymentMethod: PaymentMethod.CASH,
    expenseDate: daysAgo(20),
    userIndex: 1,
    note: 'Printer paper and supplies',
  },
  {
    categoryIndex: 5,
    amount: 1500,
    paymentMethod: PaymentMethod.CASH,
    expenseDate: daysAgo(15),
    userIndex: 1,
    note: 'Delivery transport',
  },
  {
    categoryIndex: 6,
    amount: 5000,
    paymentMethod: PaymentMethod.BKASH,
    expenseDate: daysAgo(10),
    userIndex: 0,
    note: 'Facebook ads',
  },
];

// Service Jobs Data
export const serviceJobsData = [
  {
    jobId: 'SRV-2024-0001',
    customerIndex: 5,
    deviceModel: 'iPhone 12',
    problemDescription: 'Screen cracked, needs replacement',
    imei: '111222333444555',
    serviceType: ServiceType.HARDWARE,
    technicianName: 'Kamal',
    estimatedDeliveryDate: daysFromNow(3),
    status: ServiceStatus.WORKING,
    serviceCharge: 8000,
    partsCost: 5000,
    totalAmount: 13000,
    paidAmount: 8000,
    dueAmount: 5000,
    paymentMethod: PaymentMethod.CASH,
    userIndex: 1,
    parts: [
      {
        usageType: PartsUsageType.OWN,
        partName: 'iPhone 12 Screen',
        quantity: 1,
        partCost: 5000,
      },
    ],
  },
  {
    jobId: 'SRV-2024-0002',
    customerIndex: 6,
    deviceModel: 'Samsung S21',
    problemDescription: 'Software issue, stuck on boot logo',
    imei: '222333444555666',
    serviceType: ServiceType.SOFTWARE,
    technicianName: 'Rahim',
    estimatedDeliveryDate: daysFromNow(1),
    status: ServiceStatus.READY,
    serviceCharge: 2000,
    partsCost: 0,
    totalAmount: 2000,
    paidAmount: 2000,
    dueAmount: 0,
    paymentMethod: PaymentMethod.BKASH,
    userIndex: 1,
    parts: [],
  },
  {
    jobId: 'SRV-2024-0003',
    customerIndex: 7,
    deviceModel: 'Xiaomi Note 11',
    problemDescription: 'Battery draining fast, charging port issue',
    imei: '333444555666777',
    serviceType: ServiceType.BOTH,
    technicianName: 'Kamal',
    estimatedDeliveryDate: daysFromNow(5),
    status: ServiceStatus.PENDING,
    serviceCharge: 3500,
    partsCost: 1500,
    totalAmount: 5000,
    paidAmount: 2000,
    dueAmount: 3000,
    paymentMethod: PaymentMethod.CASH,
    userIndex: 1,
    parts: [
      {
        usageType: PartsUsageType.OWN,
        partName: 'Charging Port',
        quantity: 1,
        partCost: 800,
      },
      {
        usageType: PartsUsageType.BORROWED,
        partName: 'Battery',
        quantity: 1,
        borrowPersonName: 'Parts Shop',
        borrowPersonPhone: '01999888777',
        borrowPricePerUnit: 700,
        totalBorrowAmount: 700,
        paidAmount: 700,
        dueAmount: 0,
      },
    ],
  },
];

// Overseas Phone Tracking Data
export const overseasTrackingData = [
  {
    phoneModel: 'iPhone 15 Pro',
    brand: 'Apple',
    imei1: '888777666555444',
    imei2: '888777666555445',
    storageVariant: '256GB',
    sourceType: SourceType.DUBAI,
    sourcePersonName: 'Ahmed Ali',
    sourcePhone: '+971501234567',
    location: 'Dubai',
    carrierIndex: 0,
    contractType: ContractType.FIXED,
    contractDetails: 'Fixed rate per shipment',
    contractStartDate: daysAgo(15),
    expectedDeliveryDate: daysFromNow(5),
    amountGiven: 140000,
    paymentMethod: PaymentMethod.BANK,
    paymentDate: daysAgo(15),
    status: OverseasPhoneStatus.WITH_CARRIER,
    note: 'Natural Titanium color',
  },
  {
    phoneModel: 'Samsung S24 Ultra',
    brand: 'Samsung',
    imei1: '999888777666555',
    imei2: undefined,
    storageVariant: '512GB',
    sourceType: SourceType.DUBAI,
    sourcePersonName: 'Mohammad Khan',
    sourcePhone: '+971509876543',
    location: 'Dubai',
    carrierIndex: 1,
    contractType: ContractType.PER_PHONE,
    contractDetails: '2000 BDT per phone',
    contractStartDate: daysAgo(10),
    expectedDeliveryDate: daysFromNow(10),
    amountGiven: 130000,
    paymentMethod: PaymentMethod.BANK,
    paymentDate: daysAgo(10),
    status: OverseasPhoneStatus.SENT_TO_CARRIER,
    note: 'Titanium Gray',
  },
  {
    phoneModel: 'Google Pixel 8',
    brand: 'Google',
    imei1: '777666555444333',
    imei2: '777666555444334',
    storageVariant: '128GB',
    sourceType: SourceType.SUPPLIER,
    sourcePersonName: 'Tokyo Mobile',
    sourcePhone: '+81312345678',
    location: 'Japan',
    carrierIndex: 2,
    contractType: ContractType.FIXED,
    contractDetails: 'Fixed shipping via Japan Post',
    contractStartDate: daysAgo(20),
    expectedDeliveryDate: daysAgo(2),
    amountGiven: 85000,
    paymentMethod: PaymentMethod.BANK,
    paymentDate: daysAgo(20),
    status: OverseasPhoneStatus.DELIVERED,
    note: 'Obsidian color - Already received',
  },
];

// Pre-orders Data
export const preOrdersData = [
  {
    orderNo: 'PO-2024-0001',
    customerIndex: 0,
    customerName: 'Rahim Ahmed',
    customerPhone: '01511111111',
    customerAddress: 'Dhanmondi, Dhaka',
    productIndex: 0,
    productName: 'iPhone 15 Pro Max 256GB',
    variantDetails: 'Blue Titanium, 256GB',
    totalPrice: 165000,
    isEmi: false,
    bookingAmount: 20000,
    paidAmount: 20000,
    paymentMethod: PaymentMethod.CASH,
    status: OrderStatus.CONFIRMED,
    expectedDeliveryDays: 7,
    note: 'Customer waiting for Blue color',
  },
  {
    orderNo: 'PO-2024-0002',
    customerIndex: 2,
    customerName: 'Fatima Begum',
    customerPhone: '01533333333',
    customerAddress: 'Mohammadpur, Dhaka',
    productIndex: 2,
    productName: 'Samsung Galaxy S24 Ultra 512GB',
    variantDetails: 'Titanium Yellow, 512GB',
    totalPrice: 155000,
    isEmi: true,
    emiDuration: EmiDuration.SIX_MONTHS,
    downPayment: 55000,
    monthlyInstallment: 17500,
    emiInterestRate: 5,
    totalPayableWithEmi: 160000,
    bookingAmount: 30000,
    paidAmount: 30000,
    paymentMethod: PaymentMethod.BKASH,
    status: OrderStatus.PROCESSING,
    expectedDeliveryDays: 14,
    note: 'EMI customer - 6 months plan',
  },
];
